[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_FIREBASE_API_KEY = "AIzaSyDIQP3Mgu1BpF4pftSelrDvE8nQSbhXwQ8"
  VITE_FIREBASE_AUTH_DOMAIN = "hackathon-79e80.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "hackathon-79e80"
  VITE_FIREBASE_STORAGE_BUCKET = "hackathon-79e80.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "338581325054"
  VITE_FIREBASE_APP_ID = "1:338581325054:web:10ad1b4e1793d5a7b491af"
  VITE_FIREBASE_MEASUREMENT_ID = "G-WN45LN4MR6"

# SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Error page redirects
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.googleapis.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.google-analytics.com wss://*.firebaseio.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"